// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZuVN23n0woh8KNrfihPe6HAZ4XfEyEtk',
    appId: '1:533052391113:web:f7e7ac4f36a2fdd9d65718',
    messagingSenderId: '533052391113',
    projectId: 'expense-tracker-ec2d7',
    authDomain: 'expense-tracker-ec2d7.firebaseapp.com',
    storageBucket: 'expense-tracker-ec2d7.firebasestorage.app',
    measurementId: 'G-0QHS3LP864',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ_LvGGL0CYKmn6136OPyYHtNd6wQQbHo',
    appId: '1:533052391113:android:dd0e005ccf061cc6d65718',
    messagingSenderId: '533052391113',
    projectId: 'expense-tracker-ec2d7',
    storageBucket: 'expense-tracker-ec2d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJkYtK_vI7RXQoDYqIR6IeypcrCg4O5ww',
    appId: '1:533052391113:ios:f87bdff51a2fd936d65718',
    messagingSenderId: '533052391113',
    projectId: 'expense-tracker-ec2d7',
    storageBucket: 'expense-tracker-ec2d7.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJkYtK_vI7RXQoDYqIR6IeypcrCg4O5ww',
    appId: '1:533052391113:ios:f87bdff51a2fd936d65718',
    messagingSenderId: '533052391113',
    projectId: 'expense-tracker-ec2d7',
    storageBucket: 'expense-tracker-ec2d7.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZuVN23n0woh8KNrfihPe6HAZ4XfEyEtk',
    appId: '1:533052391113:web:2fa176e7037d109cd65718',
    messagingSenderId: '533052391113',
    projectId: 'expense-tracker-ec2d7',
    authDomain: 'expense-tracker-ec2d7.firebaseapp.com',
    storageBucket: 'expense-tracker-ec2d7.firebasestorage.app',
    measurementId: 'G-B7BBE9CH8X',
  );
}
