// import 'package:expense_tracker/models/category.dart';
// import 'package:expense_tracker/models/transaction.dart';
// import 'package:flutter/material.dart';
// import 'package:font_awesome_flutter/font_awesome_flutter.dart';

// final List<Category> mockCategories = [
//   Category(name: 'Food', icon: FontAwesomeIcons.utensils, color: const Color(0xFFE57373)), 
//   Category(name: 'Transport', icon: FontAwesomeIcons.car, color: const Color(0xFF7986CB)), 
//   Category(name: 'Shopping', icon: FontAwesomeIcons.bagShopping, color: const Color(0xFFFFB74D)), 
//   Category(name: 'Fun', icon: FontAwesomeIcons.gamepad, color: const Color(0xFFBA68C8)), 
//   Category(name: 'Work', icon: FontAwesomeIcons.briefcase, color: const Color(0xFF4DB6AC)), 
//   Category(name: 'Health', icon: FontAwesomeIcons.heartPulse, color: const Color(0xFFF06292)), 
//   Category(name: 'Education', icon: FontAwesomeIcons.graduationCap, color: const Color(0xFF64B5F6)), 
//   Category(name: 'Others', icon: FontAwesomeIcons.ellipsis, color: const Color(0xFF90A4AE)), 
// ];

// final List<Transaction> mockTransactions = [
//   Transaction(
//     title: 'Grocery Shopping',
//     subtitle: 'Food & Dining • 2:30 PM',
//     amount: 45.20,
//     type: TransactionType.expense,
//     icon: FontAwesomeIcons.cartShopping,
//     iconColor: Colors.red.shade700,
//     backgroundColor: Colors.red.shade100,
//     category: 'Food',
//     date: DateTime.now(),
//   ),
//   Transaction(
//     title: 'Monthly Salary',
//     subtitle: 'Income • 10:15 AM',
//     amount: 3200.00,
//     type: TransactionType.income,
//     icon: FontAwesomeIcons.moneyBillWave,
//     iconColor: Colors.green.shade700,
//     backgroundColor: Colors.green.shade100,
//     category: 'Work',
//     date: DateTime.now(),
//   ),
//   Transaction(
//     title: 'Gas Station',
//     subtitle: 'Transport, 6:45 PM',
//     amount: 52.00,
//     type: TransactionType.expense,
//     icon: FontAwesomeIcons.gasPump,
//     iconColor: Colors.blue.shade700,
//     backgroundColor: Colors.blue.shade100,
//     category: 'Transport',
//     date: DateTime.now().subtract(const Duration(days: 1)),
//   ),
//   Transaction(
//     title: 'Starbucks',
//     subtitle: 'Food & Dining • 7:45 AM',
//     amount: 5.95,
//     type: TransactionType.expense,
//     icon: FontAwesomeIcons.mugSaucer,
//     iconColor: Colors.brown.shade700,
//     backgroundColor: Colors.brown.shade100,
//     category: 'Food',
//     date: DateTime.now().subtract(const Duration(days: 1)),
//   ),
//   Transaction(
//     title: 'Uber Ride',
//     subtitle: 'Transport • 8:00 PM',
//     amount: 15.50,
//     type: TransactionType.expense,
//     icon: FontAwesomeIcons.car,
//     iconColor: Colors.indigo.shade700,
//     backgroundColor: Colors.indigo.shade100,
//     category: 'Transport',
//     date: DateTime.now().subtract(const Duration(days: 2)),
//   ),
//   Transaction(
//     title: 'Netflix Subscription',
//     subtitle: 'Fun • 12:00 PM',
//     amount: 9.99,
//     type: TransactionType.expense,
//     icon: FontAwesomeIcons.gamepad,
//     iconColor: Colors.purple.shade700,
//     backgroundColor: Colors.purple.shade100,
//     category: 'Fun',
//     date: DateTime.now().subtract(const Duration(days: 3)),
//   ),
//   Transaction(
//     title: 'Pharmacy',
//     subtitle: 'Health • 11:00 AM',
//     amount: 12.30,
//     type: TransactionType.expense,
//     icon: FontAwesomeIcons.heartPulse,
//     iconColor: Colors.pink.shade700,
//     backgroundColor: Colors.pink.shade100,
//     category: 'Health',
//     date: DateTime.now().subtract(const Duration(days: 4)),
//   ),
//   Transaction(
//     title: 'Coursera Course',
//     subtitle: 'Education • 10:00 AM',
//     amount: 49.99,
//     type: TransactionType.expense,
//     icon: FontAwesomeIcons.graduationCap,
//     iconColor: Colors.orange.shade700,
//     backgroundColor: Colors.orange.shade100,
//     category: 'Education',
//     date: DateTime.now().subtract(const Duration(days: 5)),
//   ),
//     Transaction(
//     title: 'Clothes',
//     subtitle: 'Shopping • 10:00 AM',
//     amount: 49.99,
//     type: TransactionType.expense,
//     icon: FontAwesomeIcons.graduationCap,
//     iconColor: Colors.orange.shade700,
//     backgroundColor: Colors.orange.shade100,
//     category: 'Shopping',
//     date: DateTime.now(),
//   ),
//    Transaction(
//     title: 'Games',
//     subtitle: 'Fun • 12:00 AM',
//     amount: 578,
//     type: TransactionType.expense,
//     icon: FontAwesomeIcons.graduationCap,
//     iconColor: Colors.orange.shade700,
//     backgroundColor: Colors.orange.shade100,
//     category: 'Fun',
//     date: DateTime.now(),
//   ),
// ];

// final List<Map<String, dynamic>> mockCategories = [
//   {
//     'name': 'Food',
//     'color': '#E57373',
//     'icon': 'utensils',
//   },
//   {
//     'name': 'Transport',
//     'color': '#7986CB',
//     'icon': 'car',
//   },
//   {
//     'name': 'Shopping',
//     'color': '#FFB74D',
//     'icon': 'bagShopping',
//   },
//   {
//     'name': 'Fun',
//     'color': '#BA68C8',
//     'icon': 'gamepad',
//   },
//   {
//     'name': 'Work',
//     'color': '#4DB6AC',
//     'icon': 'briefcase',
//   },
//   {
//     'name': 'Health',
//     'color': '#F06292',
//     'icon': 'heartPulse',
//   },
//   {
//     'name': 'Education',
//     'color': '#64B5F6',
//     'icon': 'graduationCap',
//   },
//   {
//     'name': 'Others',
//     'color': '#90A4AE',
//     'icon': 'ellipsis',
//   },
// ];